name = "portafolio-apiv1"
compatibility_date = "2025-02-09"
account_id = "53a6f662dfdab5395a90a128cb2e1f93"
workers_dev = true  # O false, según tu preferencia
main = "src/index.ts"

# Si workers_dev = false, define las rutas de tu Worker
# [[routes]]
# pattern = "tu-dominio.com/*"
# zone_id = "tu_zone_id"
